name: Android Debug APK
on:
  workflow_dispatch:
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OS deps
        run: sudo apt-get update && sudo apt-get install -y patch

      - uses: actions/setup-node@v4
        with: { node-version: 22.18.0, cache: 'npm' }

      - name: Install JS deps (app)
        run: npm ci --no-audit --no-fund

      - name: Build local plugin (if present)
        run: |
          if [ -d cordova-plugin-moodleapp ]; then
            cd cordova-plugin-moodleapp
            npm ci || true
            npm run build || true
            cd ..
          fi

      - name: Web build (www/)
        run: npx --yes @ionic/cli@latest ionic build

      - name: Ensure Capacitor CLI & Android platform
        run: |
          npx --yes @capacitor/cli@latest cap --version
          if [ ! -d android ]; then
            npx --yes @capacitor/cli@latest cap add android
          fi
          npx --yes @capacitor/cli@latest cap sync android

      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }

      - uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK pieces
        run: |
          yes | sdkmanager --licenses >/dev/null
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Build debug APK
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: moodleapp-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
